-dontwarn org.jetbrains.skia.**
-keep class org.jetbrains.skia.** { *; }
-dontwarn org.jetbrains.skiko.**
-keep class org.jetbrains.skiko.** { *; }
-keep class org.jetbrains.compose.ui.tooling.preview.Preview { *; }
